name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Publish Docker Image
      run: |
          # login to GitHub Container Registry
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u nikosnikolaidis --password-stdin
          # build image
          docker build . --tag nikosnikolaidis/test:$(date +'%Y-%m-%d')-1
          # push image
          docker push  nikosnikolaidis/test:$(date +'%Y-%m-%d')-1
